CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(120),
  slug VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT uk_users_tenant_email UNIQUE (tenant_id, email)
);

CREATE TABLE IF NOT EXISTS dealerships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(120),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_dealer_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  dealership_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(255),
  city VARCHAR(120),
  budget_min INT,
  budget_max INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_customer_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_customer_dealer FOREIGN KEY (dealership_id) REFERENCES dealerships(id)
);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  dealership_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  source VARCHAR(120) NOT NULL,
  interest VARCHAR(255) NOT NULL,
  status VARCHAR(40) NOT NULL,
  expected_price INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lead_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_lead_dealer FOREIGN KEY (dealership_id) REFERENCES dealerships(id),
  CONSTRAINT fk_lead_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  dealership_id BIGINT NOT NULL,
  stock_code VARCHAR(80) NOT NULL,
  title VARCHAR(255) NOT NULL,
  make_name VARCHAR(120) NOT NULL,
  model_name VARCHAR(120) NOT NULL,
  vehicle_year INT NOT NULL,
  fuel VARCHAR(40) NOT NULL,
  transmission VARCHAR(40) NOT NULL,
  mileage_km INT NOT NULL,
  price INT NOT NULL,
  purchase_price INT NOT NULL,
  color VARCHAR(80),
  status VARCHAR(40) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vehicle_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_vehicle_dealer FOREIGN KEY (dealership_id) REFERENCES dealerships(id),
  CONSTRAINT uk_vehicle_tenant_stock UNIQUE (tenant_id, stock_code)
);

CREATE TABLE IF NOT EXISTS follow_ups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  dealership_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  lead_id BIGINT,
  title VARCHAR(255) NOT NULL,
  due_at TIMESTAMP NOT NULL,
  notes TEXT,
  status VARCHAR(40) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_follow_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_follow_dealer FOREIGN KEY (dealership_id) REFERENCES dealerships(id),
  CONSTRAINT fk_follow_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_follow_lead FOREIGN KEY (lead_id) REFERENCES leads(id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  dealership_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  vehicle_id BIGINT NOT NULL,
  amount INT NOT NULL,
  payment_mode VARCHAR(80) NOT NULL,
  delivery_date DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_booking_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_booking_dealer FOREIGN KEY (dealership_id) REFERENCES dealerships(id),
  CONSTRAINT fk_booking_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_booking_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);
